-- =====================================================================
-- Migração: incidência por bolinhas (nivel 1..5) em vez de porcentagem
-- =====================================================================
-- Rode UMA vez no SQL Editor. Adiciona a coluna `nivel` em modulos e
-- aulas, define o nível de cada item e remove a porcentagem do texto.
-- Não apaga vídeos nem questões já cadastrados.
-- =====================================================================

alter table public.modulos add column if not exists nivel integer not null default 3;
alter table public.aulas   add column if not exists nivel integer not null default 3;

-- Matemática
update public.modulos set nivel = 5, descricao = '' where nome = 'Matemática Básica' and materia_id = (select id from public.materias where nome = 'Matemática');
update public.aulas set nivel = 5, resumo = 'o assunto isolado mais cobrado de toda a prova' where titulo = 'Razão e proporção' and modulo_id = (select id from public.modulos where nome = 'Matemática Básica' and materia_id = (select id from public.materias where nome = 'Matemática'));
update public.aulas set nivel = 3, resumo = '' where titulo = 'Porcentagem' and modulo_id = (select id from public.modulos where nome = 'Matemática Básica' and materia_id = (select id from public.materias where nome = 'Matemática'));
update public.aulas set nivel = 2, resumo = '' where titulo = 'Expressões numéricas, lógica matemática e operações' and modulo_id = (select id from public.modulos where nome = 'Matemática Básica' and materia_id = (select id from public.materias where nome = 'Matemática'));
update public.aulas set nivel = 2, resumo = '' where titulo = 'Sistemas de numeração e sistema métrico decimal' and modulo_id = (select id from public.modulos where nome = 'Matemática Básica' and materia_id = (select id from public.materias where nome = 'Matemática'));
update public.aulas set nivel = 1, resumo = '' where titulo = 'MMC e MDC' and modulo_id = (select id from public.modulos where nome = 'Matemática Básica' and materia_id = (select id from public.materias where nome = 'Matemática'));
update public.modulos set nivel = 4, descricao = '' where nome = 'Geometria' and materia_id = (select id from public.materias where nome = 'Matemática');
update public.aulas set nivel = 5, resumo = '' where titulo = 'Geometria espacial (prismas e cilindros)' and modulo_id = (select id from public.modulos where nome = 'Geometria' and materia_id = (select id from public.materias where nome = 'Matemática'));
update public.aulas set nivel = 4, resumo = '' where titulo = 'Geometria plana (cálculo de áreas)' and modulo_id = (select id from public.modulos where nome = 'Geometria' and materia_id = (select id from public.materias where nome = 'Matemática'));
update public.aulas set nivel = 2, resumo = '' where titulo = 'Geometria analítica (reta e circunferência)' and modulo_id = (select id from public.modulos where nome = 'Geometria' and materia_id = (select id from public.materias where nome = 'Matemática'));
update public.modulos set nivel = 3, descricao = '' where nome = 'Funções e Equações' and materia_id = (select id from public.materias where nome = 'Matemática');
update public.aulas set nivel = 3, resumo = '' where titulo = 'Gráficos de funções' and modulo_id = (select id from public.modulos where nome = 'Funções e Equações' and materia_id = (select id from public.materias where nome = 'Matemática'));
update public.aulas set nivel = 3, resumo = 'a mais cobrada entre as funções' where titulo = 'Função afim (1º grau)' and modulo_id = (select id from public.modulos where nome = 'Funções e Equações' and materia_id = (select id from public.materias where nome = 'Matemática'));
update public.aulas set nivel = 3, resumo = '' where titulo = 'Funções de várias sentenças, modular e inequações' and modulo_id = (select id from public.modulos where nome = 'Funções e Equações' and materia_id = (select id from public.materias where nome = 'Matemática'));
update public.aulas set nivel = 2, resumo = '' where titulo = 'Exponencial e logaritmo' and modulo_id = (select id from public.modulos where nome = 'Funções e Equações' and materia_id = (select id from public.materias where nome = 'Matemática'));
update public.aulas set nivel = 2, resumo = '' where titulo = 'Função quadrática (2º grau)' and modulo_id = (select id from public.modulos where nome = 'Funções e Equações' and materia_id = (select id from public.materias where nome = 'Matemática'));
update public.aulas set nivel = 2, resumo = '' where titulo = 'Funções trigonométricas' and modulo_id = (select id from public.modulos where nome = 'Funções e Equações' and materia_id = (select id from public.materias where nome = 'Matemática'));
update public.modulos set nivel = 3, descricao = '' where nome = 'Estatística' and materia_id = (select id from public.materias where nome = 'Matemática');
update public.aulas set nivel = 4, resumo = '' where titulo = 'Interpretação de gráficos (barras, linhas, pizza)' and modulo_id = (select id from public.modulos where nome = 'Estatística' and materia_id = (select id from public.materias where nome = 'Matemática'));
update public.aulas set nivel = 4, resumo = '' where titulo = 'Leitura e análise direta de dados estatísticos' and modulo_id = (select id from public.modulos where nome = 'Estatística' and materia_id = (select id from public.materias where nome = 'Matemática'));
update public.aulas set nivel = 3, resumo = '' where titulo = 'Médias contextualizadas (idade, altura, salário)' and modulo_id = (select id from public.modulos where nome = 'Estatística' and materia_id = (select id from public.materias where nome = 'Matemática'));
update public.aulas set nivel = 2, resumo = '' where titulo = 'Média ponderada' and modulo_id = (select id from public.modulos where nome = 'Estatística' and materia_id = (select id from public.materias where nome = 'Matemática'));
update public.modulos set nivel = 2, descricao = '' where nome = 'Probabilidade' and materia_id = (select id from public.materias where nome = 'Matemática');
update public.aulas set nivel = 5, resumo = 'tema muito temido, grande diversidade de questões' where titulo = 'Probabilidade' and modulo_id = (select id from public.modulos where nome = 'Probabilidade' and materia_id = (select id from public.materias where nome = 'Matemática'));
update public.aulas set nivel = 3, resumo = '' where titulo = 'Análise combinatória (arranjo e combinação)' and modulo_id = (select id from public.modulos where nome = 'Probabilidade' and materia_id = (select id from public.materias where nome = 'Matemática'));
update public.aulas set nivel = 3, resumo = '' where titulo = 'Permutação' and modulo_id = (select id from public.modulos where nome = 'Probabilidade' and materia_id = (select id from public.materias where nome = 'Matemática'));
update public.aulas set nivel = 2, resumo = '' where titulo = 'Princípio fundamental da contagem' and modulo_id = (select id from public.modulos where nome = 'Probabilidade' and materia_id = (select id from public.materias where nome = 'Matemática'));
update public.modulos set nivel = 2, descricao = '' where nome = 'Outros temas' and materia_id = (select id from public.materias where nome = 'Matemática');
update public.aulas set nivel = 4, resumo = '' where titulo = 'Progressões (PA e PG)' and modulo_id = (select id from public.modulos where nome = 'Outros temas' and materia_id = (select id from public.materias where nome = 'Matemática'));
update public.aulas set nivel = 4, resumo = '' where titulo = 'Trigonometria (triângulo retângulo e gráficos)' and modulo_id = (select id from public.modulos where nome = 'Outros temas' and materia_id = (select id from public.materias where nome = 'Matemática'));
update public.aulas set nivel = 3, resumo = '' where titulo = 'Conjuntos (diagrama de Venn)' and modulo_id = (select id from public.modulos where nome = 'Outros temas' and materia_id = (select id from public.materias where nome = 'Matemática'));
update public.aulas set nivel = 1, resumo = '' where titulo = 'Matrizes' and modulo_id = (select id from public.modulos where nome = 'Outros temas' and materia_id = (select id from public.materias where nome = 'Matemática'));
update public.aulas set nivel = 1, resumo = '' where titulo = 'Sistemas lineares' and modulo_id = (select id from public.modulos where nome = 'Outros temas' and materia_id = (select id from public.materias where nome = 'Matemática'));

-- Biologia
update public.modulos set nivel = 5, descricao = '' where nome = 'Ecologia' and materia_id = (select id from public.materias where nome = 'Biologia');
update public.aulas set nivel = 3, resumo = '' where titulo = 'Poluição' and modulo_id = (select id from public.modulos where nome = 'Ecologia' and materia_id = (select id from public.materias where nome = 'Biologia'));
update public.aulas set nivel = 3, resumo = '' where titulo = 'Desequilíbrios ecológicos' and modulo_id = (select id from public.modulos where nome = 'Ecologia' and materia_id = (select id from public.materias where nome = 'Biologia'));
update public.aulas set nivel = 3, resumo = '' where titulo = 'Ciclos de matéria' and modulo_id = (select id from public.modulos where nome = 'Ecologia' and materia_id = (select id from public.materias where nome = 'Biologia'));
update public.modulos set nivel = 2, descricao = '' where nome = 'Fisiologia Animal' and materia_id = (select id from public.materias where nome = 'Biologia');
update public.aulas set nivel = 3, resumo = '' where titulo = 'Sistema digestório' and modulo_id = (select id from public.modulos where nome = 'Fisiologia Animal' and materia_id = (select id from public.materias where nome = 'Biologia'));
update public.aulas set nivel = 3, resumo = '' where titulo = 'Sistema endócrino (hormônios)' and modulo_id = (select id from public.modulos where nome = 'Fisiologia Animal' and materia_id = (select id from public.materias where nome = 'Biologia'));
update public.modulos set nivel = 2, descricao = '' where nome = 'Botânica' and materia_id = (select id from public.materias where nome = 'Biologia');
update public.aulas set nivel = 3, resumo = '' where titulo = 'Grupos de plantas (Angiospermas e Gimnospermas)' and modulo_id = (select id from public.modulos where nome = 'Botânica' and materia_id = (select id from public.materias where nome = 'Biologia'));
update public.aulas set nivel = 3, resumo = '' where titulo = 'Adaptações das plantas aos ecossistemas' and modulo_id = (select id from public.modulos where nome = 'Botânica' and materia_id = (select id from public.materias where nome = 'Biologia'));
update public.modulos set nivel = 2, descricao = '' where nome = 'Bioenergética' and materia_id = (select id from public.materias where nome = 'Biologia');
update public.aulas set nivel = 3, resumo = '' where titulo = 'Fermentação (álcool, massas)' and modulo_id = (select id from public.modulos where nome = 'Bioenergética' and materia_id = (select id from public.materias where nome = 'Biologia'));
update public.aulas set nivel = 3, resumo = '' where titulo = 'Fotossíntese' and modulo_id = (select id from public.modulos where nome = 'Bioenergética' and materia_id = (select id from public.materias where nome = 'Biologia'));
update public.aulas set nivel = 3, resumo = '' where titulo = 'Respiração celular' and modulo_id = (select id from public.modulos where nome = 'Bioenergética' and materia_id = (select id from public.materias where nome = 'Biologia'));
update public.modulos set nivel = 2, descricao = '' where nome = 'Biologia Molecular e Engenharia Genética' and materia_id = (select id from public.materias where nome = 'Biologia');
update public.aulas set nivel = 3, resumo = '' where titulo = 'Transgênicos' and modulo_id = (select id from public.modulos where nome = 'Biologia Molecular e Engenharia Genética' and materia_id = (select id from public.materias where nome = 'Biologia'));
update public.aulas set nivel = 3, resumo = '' where titulo = 'Terapia gênica' and modulo_id = (select id from public.modulos where nome = 'Biologia Molecular e Engenharia Genética' and materia_id = (select id from public.materias where nome = 'Biologia'));
update public.aulas set nivel = 3, resumo = '' where titulo = 'Teste de DNA' and modulo_id = (select id from public.modulos where nome = 'Biologia Molecular e Engenharia Genética' and materia_id = (select id from public.materias where nome = 'Biologia'));
update public.modulos set nivel = 2, descricao = '' where nome = 'Evolução' and materia_id = (select id from public.materias where nome = 'Biologia');
update public.aulas set nivel = 3, resumo = '' where titulo = 'Teorias evolutivas' and modulo_id = (select id from public.modulos where nome = 'Evolução' and materia_id = (select id from public.materias where nome = 'Biologia'));
update public.aulas set nivel = 3, resumo = '' where titulo = 'Resistência bacteriana a antibióticos' and modulo_id = (select id from public.modulos where nome = 'Evolução' and materia_id = (select id from public.materias where nome = 'Biologia'));
update public.aulas set nivel = 3, resumo = '' where titulo = 'Processos de especiação' and modulo_id = (select id from public.modulos where nome = 'Evolução' and materia_id = (select id from public.materias where nome = 'Biologia'));
update public.modulos set nivel = 1, descricao = '' where nome = 'Genética' and materia_id = (select id from public.materias where nome = 'Biologia');
update public.aulas set nivel = 3, resumo = '' where titulo = 'Heredogramas' and modulo_id = (select id from public.modulos where nome = 'Genética' and materia_id = (select id from public.materias where nome = 'Biologia'));
update public.aulas set nivel = 3, resumo = '' where titulo = 'Tipos de herança (recessiva/dominante, autossômica/sexual)' and modulo_id = (select id from public.modulos where nome = 'Genética' and materia_id = (select id from public.materias where nome = 'Biologia'));
update public.modulos set nivel = 1, descricao = '' where nome = 'Bioquímica' and materia_id = (select id from public.materias where nome = 'Biologia');
update public.aulas set nivel = 3, resumo = 'os temas que mais caem' where titulo = 'Água e sais minerais' and modulo_id = (select id from public.modulos where nome = 'Bioquímica' and materia_id = (select id from public.materias where nome = 'Biologia'));
update public.modulos set nivel = 1, descricao = '' where nome = 'Microbiologia' and materia_id = (select id from public.materias where nome = 'Biologia');
update public.aulas set nivel = 3, resumo = 'foco em transmissão e prevenção' where titulo = 'Doenças (dengue, gripe, aids, Chagas, leishmaniose, malária)' and modulo_id = (select id from public.modulos where nome = 'Microbiologia' and materia_id = (select id from public.materias where nome = 'Biologia'));
update public.modulos set nivel = 1, descricao = '' where nome = 'Histologia Animal' and materia_id = (select id from public.materias where nome = 'Biologia');
update public.aulas set nivel = 3, resumo = '' where titulo = 'Sangue e sistema imune' and modulo_id = (select id from public.modulos where nome = 'Histologia Animal' and materia_id = (select id from public.materias where nome = 'Biologia'));
update public.aulas set nivel = 3, resumo = '' where titulo = 'Vacinas' and modulo_id = (select id from public.modulos where nome = 'Histologia Animal' and materia_id = (select id from public.materias where nome = 'Biologia'));
update public.modulos set nivel = 1, descricao = '' where nome = 'Núcleo e Divisão Celular' and materia_id = (select id from public.materias where nome = 'Biologia');
update public.aulas set nivel = 3, resumo = '' where titulo = 'Ativação de genes e especialização celular' and modulo_id = (select id from public.modulos where nome = 'Núcleo e Divisão Celular' and materia_id = (select id from public.materias where nome = 'Biologia'));
update public.aulas set nivel = 3, resumo = '' where titulo = 'Célula-tronco e clonagem' and modulo_id = (select id from public.modulos where nome = 'Núcleo e Divisão Celular' and materia_id = (select id from public.materias where nome = 'Biologia'));
update public.aulas set nivel = 3, resumo = '' where titulo = 'Fases da divisão celular' and modulo_id = (select id from public.modulos where nome = 'Núcleo e Divisão Celular' and materia_id = (select id from public.materias where nome = 'Biologia'));
update public.modulos set nivel = 1, descricao = '' where nome = 'Zoologia' and materia_id = (select id from public.materias where nome = 'Biologia');
update public.aulas set nivel = 3, resumo = '' where titulo = 'Doenças causadas por vermes, artrópodes e vertebrados' and modulo_id = (select id from public.modulos where nome = 'Zoologia' and materia_id = (select id from public.materias where nome = 'Biologia'));
update public.modulos set nivel = 1, descricao = '' where nome = 'Características dos Seres Vivos e Origem da Vida' and materia_id = (select id from public.materias where nome = 'Biologia');
update public.aulas set nivel = 3, resumo = '' where titulo = 'Características dos seres vivos' and modulo_id = (select id from public.modulos where nome = 'Características dos Seres Vivos e Origem da Vida' and materia_id = (select id from public.materias where nome = 'Biologia'));
update public.aulas set nivel = 3, resumo = '' where titulo = 'Reprodução humana e embriologia' and modulo_id = (select id from public.modulos where nome = 'Características dos Seres Vivos e Origem da Vida' and materia_id = (select id from public.materias where nome = 'Biologia'));
update public.aulas set nivel = 3, resumo = '' where titulo = 'Origem da vida e taxonomia' and modulo_id = (select id from public.modulos where nome = 'Características dos Seres Vivos e Origem da Vida' and materia_id = (select id from public.materias where nome = 'Biologia'));
update public.modulos set nivel = 1, descricao = '' where nome = 'Ciclo do Nitrogênio' and materia_id = (select id from public.materias where nome = 'Biologia');
update public.aulas set nivel = 3, resumo = '' where titulo = 'Ciclo do nitrogênio' and modulo_id = (select id from public.modulos where nome = 'Ciclo do Nitrogênio' and materia_id = (select id from public.materias where nome = 'Biologia'));
update public.modulos set nivel = 1, descricao = '' where nome = 'Citologia' and materia_id = (select id from public.materias where nome = 'Biologia');
update public.aulas set nivel = 3, resumo = 'o tema que mais cai' where titulo = 'Organelas celulares' and modulo_id = (select id from public.modulos where nome = 'Citologia' and materia_id = (select id from public.materias where nome = 'Biologia'));

-- Física
update public.modulos set nivel = 4, descricao = '' where nome = 'Eletrodinâmica' and materia_id = (select id from public.materias where nome = 'Física');
update public.aulas set nivel = 5, resumo = '' where titulo = 'Circuitos elétricos e associação de resistores' and modulo_id = (select id from public.modulos where nome = 'Eletrodinâmica' and materia_id = (select id from public.materias where nome = 'Física'));
update public.aulas set nivel = 4, resumo = '' where titulo = 'Potência e energia elétrica' and modulo_id = (select id from public.modulos where nome = 'Eletrodinâmica' and materia_id = (select id from public.materias where nome = 'Física'));
update public.aulas set nivel = 3, resumo = '' where titulo = 'Leis de Ohm' and modulo_id = (select id from public.modulos where nome = 'Eletrodinâmica' and materia_id = (select id from public.materias where nome = 'Física'));
update public.modulos set nivel = 3, descricao = '' where nome = 'Dinâmica' and materia_id = (select id from public.materias where nome = 'Física');
update public.aulas set nivel = 5, resumo = '' where titulo = 'Trabalho e energia' and modulo_id = (select id from public.modulos where nome = 'Dinâmica' and materia_id = (select id from public.materias where nome = 'Física'));
update public.aulas set nivel = 4, resumo = '' where titulo = 'Leis de Newton' and modulo_id = (select id from public.modulos where nome = 'Dinâmica' and materia_id = (select id from public.materias where nome = 'Física'));
update public.aulas set nivel = 2, resumo = '' where titulo = 'Quantidade de movimento e impulso' and modulo_id = (select id from public.modulos where nome = 'Dinâmica' and materia_id = (select id from public.materias where nome = 'Física'));
update public.modulos set nivel = 3, descricao = '' where nome = 'Termologia' and materia_id = (select id from public.materias where nome = 'Física');
update public.aulas set nivel = 4, resumo = '' where titulo = 'Calorimetria (calor sensível e latente)' and modulo_id = (select id from public.modulos where nome = 'Termologia' and materia_id = (select id from public.materias where nome = 'Física'));
update public.aulas set nivel = 4, resumo = '' where titulo = 'Transmissão de calor (condução, convecção, radiação)' and modulo_id = (select id from public.modulos where nome = 'Termologia' and materia_id = (select id from public.materias where nome = 'Física'));
update public.aulas set nivel = 3, resumo = '' where titulo = 'Termodinâmica (transformações gasosas)' and modulo_id = (select id from public.modulos where nome = 'Termologia' and materia_id = (select id from public.materias where nome = 'Física'));
update public.modulos set nivel = 3, descricao = '' where nome = 'Ondulatória' and materia_id = (select id from public.materias where nome = 'Física');
update public.aulas set nivel = 5, resumo = '' where titulo = 'Fenômenos ondulatórios (conceitos gerais)' and modulo_id = (select id from public.modulos where nome = 'Ondulatória' and materia_id = (select id from public.materias where nome = 'Física'));
update public.aulas set nivel = 4, resumo = '' where titulo = 'Ondas aplicadas à Óptica' and modulo_id = (select id from public.modulos where nome = 'Ondulatória' and materia_id = (select id from public.materias where nome = 'Física'));
update public.aulas set nivel = 2, resumo = '' where titulo = 'Equação fundamental da ondulatória' and modulo_id = (select id from public.modulos where nome = 'Ondulatória' and materia_id = (select id from public.materias where nome = 'Física'));
update public.modulos set nivel = 2, descricao = '' where nome = 'Cinemática' and materia_id = (select id from public.materias where nome = 'Física');
update public.aulas set nivel = 5, resumo = '' where titulo = 'MU e MUV' and modulo_id = (select id from public.modulos where nome = 'Cinemática' and materia_id = (select id from public.materias where nome = 'Física'));
update public.aulas set nivel = 4, resumo = '' where titulo = 'Lançamentos e queda livre' and modulo_id = (select id from public.modulos where nome = 'Cinemática' and materia_id = (select id from public.materias where nome = 'Física'));
update public.aulas set nivel = 2, resumo = '' where titulo = 'MCU (movimento circular uniforme)' and modulo_id = (select id from public.modulos where nome = 'Cinemática' and materia_id = (select id from public.materias where nome = 'Física'));
update public.modulos set nivel = 2, descricao = '' where nome = 'Óptica' and materia_id = (select id from public.materias where nome = 'Física');
update public.aulas set nivel = 4, resumo = '' where titulo = 'Fundamentos da óptica (cor dos corpos, meios materiais)' and modulo_id = (select id from public.modulos where nome = 'Óptica' and materia_id = (select id from public.materias where nome = 'Física'));
update public.aulas set nivel = 4, resumo = '' where titulo = 'Refração' and modulo_id = (select id from public.modulos where nome = 'Óptica' and materia_id = (select id from public.materias where nome = 'Física'));
update public.aulas set nivel = 4, resumo = '' where titulo = 'Defeitos da visão (miopia, hipermetropia, astigmatismo, presbiopia)' and modulo_id = (select id from public.modulos where nome = 'Óptica' and materia_id = (select id from public.materias where nome = 'Física'));
update public.modulos set nivel = 3, descricao = '' where nome = 'Estática, Gravitação, Eletromagnetismo e Hidrostática' and materia_id = (select id from public.materias where nome = 'Física');
update public.aulas set nivel = 4, resumo = '' where titulo = 'Hidrostática (pressão e densidade)' and modulo_id = (select id from public.modulos where nome = 'Estática, Gravitação, Eletromagnetismo e Hidrostática' and materia_id = (select id from public.materias where nome = 'Física'));
update public.aulas set nivel = 4, resumo = '' where titulo = 'Eletromagnetismo (força magnética, Faraday, Lenz)' and modulo_id = (select id from public.modulos where nome = 'Estática, Gravitação, Eletromagnetismo e Hidrostática' and materia_id = (select id from public.materias where nome = 'Física'));
update public.aulas set nivel = 3, resumo = '' where titulo = 'Eletrostática (carga, campo e potencial elétrico)' and modulo_id = (select id from public.modulos where nome = 'Estática, Gravitação, Eletromagnetismo e Hidrostática' and materia_id = (select id from public.materias where nome = 'Física'));
update public.aulas set nivel = 2, resumo = '' where titulo = 'Estática (equilíbrio de ponto material e corpo extenso)' and modulo_id = (select id from public.modulos where nome = 'Estática, Gravitação, Eletromagnetismo e Hidrostática' and materia_id = (select id from public.materias where nome = 'Física'));
update public.aulas set nivel = 1, resumo = '' where titulo = 'Gravitação (Lei da Gravitação de Newton)' and modulo_id = (select id from public.modulos where nome = 'Estática, Gravitação, Eletromagnetismo e Hidrostática' and materia_id = (select id from public.materias where nome = 'Física'));
update public.aulas set nivel = 1, resumo = '' where titulo = 'Hidrodinâmica (vazão)' and modulo_id = (select id from public.modulos where nome = 'Estática, Gravitação, Eletromagnetismo e Hidrostática' and materia_id = (select id from public.materias where nome = 'Física'));

-- Química
update public.modulos set nivel = 5, descricao = '' where nome = 'Físico-Química' and materia_id = (select id from public.materias where nome = 'Química');
update public.aulas set nivel = 5, resumo = 'ponto de partida do estudo' where titulo = 'Química Geral (átomos, substâncias, misturas, separação, densidade)' and modulo_id = (select id from public.modulos where nome = 'Físico-Química' and materia_id = (select id from public.materias where nome = 'Química'));
update public.aulas set nivel = 4, resumo = '' where titulo = 'Estequiometria' and modulo_id = (select id from public.modulos where nome = 'Físico-Química' and materia_id = (select id from public.materias where nome = 'Química'));
update public.aulas set nivel = 3, resumo = '' where titulo = 'Ácidos e bases (pH, pOH, hidrólise de sais)' and modulo_id = (select id from public.modulos where nome = 'Físico-Química' and materia_id = (select id from public.materias where nome = 'Química'));
update public.aulas set nivel = 2, resumo = 'base da eletroquímica' where titulo = 'Oxirredução / Nox' and modulo_id = (select id from public.modulos where nome = 'Físico-Química' and materia_id = (select id from public.materias where nome = 'Química'));
update public.aulas set nivel = 3, resumo = 'temas específicos recorrentes' where titulo = 'Soluções, entalpia (Lei de Hess), pilhas, radioatividade, cinética e osmose' and modulo_id = (select id from public.modulos where nome = 'Físico-Química' and materia_id = (select id from public.materias where nome = 'Química'));
update public.modulos set nivel = 4, descricao = '' where nome = 'Química Ambiental' and materia_id = (select id from public.materias where nome = 'Química');
update public.aulas set nivel = 3, resumo = '' where titulo = 'Chuva ácida' and modulo_id = (select id from public.modulos where nome = 'Química Ambiental' and materia_id = (select id from public.materias where nome = 'Química'));
update public.aulas set nivel = 3, resumo = '' where titulo = 'Buraco na camada de ozônio' and modulo_id = (select id from public.modulos where nome = 'Química Ambiental' and materia_id = (select id from public.materias where nome = 'Química'));
update public.aulas set nivel = 3, resumo = '' where titulo = 'Efeito estufa' and modulo_id = (select id from public.modulos where nome = 'Química Ambiental' and materia_id = (select id from public.materias where nome = 'Química'));
update public.modulos set nivel = 4, descricao = '' where nome = 'Química Orgânica' and materia_id = (select id from public.materias where nome = 'Química');
update public.aulas set nivel = 5, resumo = '' where titulo = 'Reações orgânicas (oxidação, saponificação, esterificação)' and modulo_id = (select id from public.modulos where nome = 'Química Orgânica' and materia_id = (select id from public.materias where nome = 'Química'));
update public.aulas set nivel = 2, resumo = '' where titulo = 'Isomeria (cis-trans e carbono quiral)' and modulo_id = (select id from public.modulos where nome = 'Química Orgânica' and materia_id = (select id from public.materias where nome = 'Química'));
update public.aulas set nivel = 2, resumo = '' where titulo = 'Classificação e propriedades das funções orgânicas' and modulo_id = (select id from public.modulos where nome = 'Química Orgânica' and materia_id = (select id from public.materias where nome = 'Química'));
update public.aulas set nivel = 2, resumo = '' where titulo = 'Nomenclatura das funções orgânicas' and modulo_id = (select id from public.modulos where nome = 'Química Orgânica' and materia_id = (select id from public.materias where nome = 'Química'));
update public.aulas set nivel = 2, resumo = '' where titulo = 'Plásticos e polímeros' and modulo_id = (select id from public.modulos where nome = 'Química Orgânica' and materia_id = (select id from public.materias where nome = 'Química'));
update public.modulos set nivel = 3, descricao = '' where nome = 'Forças Intermoleculares e Ligações Químicas' and materia_id = (select id from public.materias where nome = 'Química');
update public.aulas set nivel = 3, resumo = '' where titulo = 'Ligações químicas (iônica, covalente e metálica)' and modulo_id = (select id from public.modulos where nome = 'Forças Intermoleculares e Ligações Químicas' and materia_id = (select id from public.materias where nome = 'Química'));
update public.aulas set nivel = 3, resumo = '' where titulo = 'Modelo atômico de Bohr (saltos de elétrons)' and modulo_id = (select id from public.modulos where nome = 'Forças Intermoleculares e Ligações Químicas' and materia_id = (select id from public.materias where nome = 'Química'));
update public.aulas set nivel = 3, resumo = 'propriedade periódica mais cobrada' where titulo = 'Eletronegatividade' and modulo_id = (select id from public.modulos where nome = 'Forças Intermoleculares e Ligações Químicas' and materia_id = (select id from public.materias where nome = 'Química'));

-- História
update public.modulos set nivel = 5, descricao = '' where nome = 'Brasil' and materia_id = (select id from public.materias where nome = 'História');
update public.aulas set nivel = 5, resumo = '' where titulo = 'Brasil República (Primeira República, Era Vargas, Regime Militar, Nova República)' and modulo_id = (select id from public.modulos where nome = 'Brasil' and materia_id = (select id from public.materias where nome = 'História'));
update public.aulas set nivel = 4, resumo = '' where titulo = 'Brasil Colônia (sistema colonial, povos indígenas, escravidão)' and modulo_id = (select id from public.modulos where nome = 'Brasil' and materia_id = (select id from public.materias where nome = 'História'));
update public.aulas set nivel = 4, resumo = '' where titulo = 'Brasil Império (Segundo Reinado, escravidão, Primeiro Reinado)' and modulo_id = (select id from public.modulos where nome = 'Brasil' and materia_id = (select id from public.materias where nome = 'História'));
update public.modulos set nivel = 5, descricao = '' where nome = 'História Geral' and materia_id = (select id from public.materias where nome = 'História');
update public.aulas set nivel = 5, resumo = '' where titulo = 'Idade Contemporânea (imperialismo, guerras mundiais, Guerra Fria)' and modulo_id = (select id from public.modulos where nome = 'História Geral' and materia_id = (select id from public.materias where nome = 'História'));
update public.aulas set nivel = 3, resumo = '' where titulo = 'Idade Moderna (absolutismo, mercantilismo, Iluminismo, Revolução Francesa)' and modulo_id = (select id from public.modulos where nome = 'História Geral' and materia_id = (select id from public.materias where nome = 'História'));
update public.aulas set nivel = 3, resumo = '' where titulo = 'Idade Média (alta e baixa Idade Média, feudalismo)' and modulo_id = (select id from public.modulos where nome = 'História Geral' and materia_id = (select id from public.materias where nome = 'História'));
update public.aulas set nivel = 2, resumo = '' where titulo = 'Antiguidade (Grécia, Roma, Antiguidade Oriental)' and modulo_id = (select id from public.modulos where nome = 'História Geral' and materia_id = (select id from public.materias where nome = 'História'));
update public.aulas set nivel = 1, resumo = '' where titulo = 'Pré-história (ondas migratórias, arte rupestre)' and modulo_id = (select id from public.modulos where nome = 'História Geral' and materia_id = (select id from public.materias where nome = 'História'));
update public.modulos set nivel = 2, descricao = '' where nome = 'História Temática' and materia_id = (select id from public.materias where nome = 'História');
update public.aulas set nivel = 3, resumo = '' where titulo = 'Historiografia e questões sociais' and modulo_id = (select id from public.modulos where nome = 'História Temática' and materia_id = (select id from public.materias where nome = 'História'));

-- Geografia
update public.modulos set nivel = 5, descricao = '' where nome = 'Geografia do Brasil' and materia_id = (select id from public.materias where nome = 'Geografia');
update public.aulas set nivel = 4, resumo = '' where titulo = 'Geografia Humana (demografia e urbanização)' and modulo_id = (select id from public.modulos where nome = 'Geografia do Brasil' and materia_id = (select id from public.materias where nome = 'Geografia'));
update public.aulas set nivel = 4, resumo = '' where titulo = 'Geografia Econômica e Agrária (estrutura fundiária, mineração, indústria, energia)' and modulo_id = (select id from public.modulos where nome = 'Geografia do Brasil' and materia_id = (select id from public.materias where nome = 'Geografia'));
update public.aulas set nivel = 3, resumo = '' where titulo = 'Geografia Física (vegetação, hidrografia, relevo, clima)' and modulo_id = (select id from public.modulos where nome = 'Geografia do Brasil' and materia_id = (select id from public.materias where nome = 'Geografia'));
update public.aulas set nivel = 2, resumo = '' where titulo = 'Meio ambiente (desmatamento e ação antrópica)' and modulo_id = (select id from public.modulos where nome = 'Geografia do Brasil' and materia_id = (select id from public.materias where nome = 'Geografia'));
update public.modulos set nivel = 5, descricao = '' where nome = 'Geografia Geral' and materia_id = (select id from public.materias where nome = 'Geografia');
update public.aulas set nivel = 4, resumo = '' where titulo = 'Geografia Física (movimentos da Terra, clima, ciclo da água, cartografia)' and modulo_id = (select id from public.modulos where nome = 'Geografia Geral' and materia_id = (select id from public.materias where nome = 'Geografia'));
update public.aulas set nivel = 3, resumo = '' where titulo = 'Geografia Econômica (geografia agrária, desenvolvimento sustentável)' and modulo_id = (select id from public.modulos where nome = 'Geografia Geral' and materia_id = (select id from public.materias where nome = 'Geografia'));
update public.aulas set nivel = 3, resumo = '' where titulo = 'Geopolítica (tensões e conflitos internacionais)' and modulo_id = (select id from public.modulos where nome = 'Geografia Geral' and materia_id = (select id from public.materias where nome = 'Geografia'));
update public.aulas set nivel = 2, resumo = '' where titulo = 'Meio ambiente (desmatamento)' and modulo_id = (select id from public.modulos where nome = 'Geografia Geral' and materia_id = (select id from public.materias where nome = 'Geografia'));
update public.aulas set nivel = 2, resumo = '' where titulo = 'Demografia' and modulo_id = (select id from public.modulos where nome = 'Geografia Geral' and materia_id = (select id from public.materias where nome = 'Geografia'));

-- Sociologia
update public.modulos set nivel = 4, descricao = '' where nome = 'Diversidade Cultural e Estratificação Social' and materia_id = (select id from public.materias where nome = 'Sociologia');
update public.aulas set nivel = 4, resumo = '' where titulo = 'Gênero' and modulo_id = (select id from public.modulos where nome = 'Diversidade Cultural e Estratificação Social' and materia_id = (select id from public.materias where nome = 'Sociologia'));
update public.aulas set nivel = 3, resumo = '' where titulo = 'Desigualdades sociais' and modulo_id = (select id from public.modulos where nome = 'Diversidade Cultural e Estratificação Social' and materia_id = (select id from public.materias where nome = 'Sociologia'));
update public.aulas set nivel = 2, resumo = '' where titulo = 'Diversidade cultural' and modulo_id = (select id from public.modulos where nome = 'Diversidade Cultural e Estratificação Social' and materia_id = (select id from public.materias where nome = 'Sociologia'));
update public.aulas set nivel = 2, resumo = '' where titulo = 'Questão racial' and modulo_id = (select id from public.modulos where nome = 'Diversidade Cultural e Estratificação Social' and materia_id = (select id from public.materias where nome = 'Sociologia'));
update public.aulas set nivel = 2, resumo = '' where titulo = 'Cultura popular e erudita' and modulo_id = (select id from public.modulos where nome = 'Diversidade Cultural e Estratificação Social' and materia_id = (select id from public.materias where nome = 'Sociologia'));
update public.aulas set nivel = 2, resumo = '' where titulo = 'Questão indígena' and modulo_id = (select id from public.modulos where nome = 'Diversidade Cultural e Estratificação Social' and materia_id = (select id from public.materias where nome = 'Sociologia'));
update public.aulas set nivel = 2, resumo = '' where titulo = 'Identidade' and modulo_id = (select id from public.modulos where nome = 'Diversidade Cultural e Estratificação Social' and materia_id = (select id from public.materias where nome = 'Sociologia'));
update public.modulos set nivel = 4, descricao = '' where nome = 'Sociologia Temática' and materia_id = (select id from public.materias where nome = 'Sociologia');
update public.aulas set nivel = 4, resumo = '' where titulo = 'Antropologia' and modulo_id = (select id from public.modulos where nome = 'Sociologia Temática' and materia_id = (select id from public.materias where nome = 'Sociologia'));
update public.aulas set nivel = 3, resumo = '' where titulo = 'Cultura e educação' and modulo_id = (select id from public.modulos where nome = 'Sociologia Temática' and materia_id = (select id from public.materias where nome = 'Sociologia'));
update public.aulas set nivel = 3, resumo = '' where titulo = 'Trabalho e economia' and modulo_id = (select id from public.modulos where nome = 'Sociologia Temática' and materia_id = (select id from public.materias where nome = 'Sociologia'));
update public.aulas set nivel = 3, resumo = '' where titulo = 'Sociologia urbana e violência' and modulo_id = (select id from public.modulos where nome = 'Sociologia Temática' and materia_id = (select id from public.materias where nome = 'Sociologia'));
update public.aulas set nivel = 2, resumo = '' where titulo = 'Sociologia da ciência e do conhecimento' and modulo_id = (select id from public.modulos where nome = 'Sociologia Temática' and materia_id = (select id from public.materias where nome = 'Sociologia'));
update public.modulos set nivel = 3, descricao = '' where nome = 'Estado, Poder e Política' and materia_id = (select id from public.materias where nome = 'Sociologia');
update public.aulas set nivel = 4, resumo = '' where titulo = 'Cidadania e direitos' and modulo_id = (select id from public.modulos where nome = 'Estado, Poder e Política' and materia_id = (select id from public.materias where nome = 'Sociologia'));
update public.aulas set nivel = 4, resumo = '' where titulo = 'Democracia e participação política' and modulo_id = (select id from public.modulos where nome = 'Estado, Poder e Política' and materia_id = (select id from public.materias where nome = 'Sociologia'));
update public.aulas set nivel = 2, resumo = '' where titulo = 'Política brasileira (patrimonialismo)' and modulo_id = (select id from public.modulos where nome = 'Estado, Poder e Política' and materia_id = (select id from public.materias where nome = 'Sociologia'));
update public.aulas set nivel = 2, resumo = '' where titulo = 'Política internacional' and modulo_id = (select id from public.modulos where nome = 'Estado, Poder e Política' and materia_id = (select id from public.materias where nome = 'Sociologia'));
update public.modulos set nivel = 3, descricao = '' where nome = 'Teoria Sociológica' and materia_id = (select id from public.materias where nome = 'Sociologia');
update public.aulas set nivel = 5, resumo = '' where titulo = 'Sociologia contemporânea (destaque para Foucault)' and modulo_id = (select id from public.modulos where nome = 'Teoria Sociológica' and materia_id = (select id from public.materias where nome = 'Sociologia'));
update public.aulas set nivel = 2, resumo = '' where titulo = 'Conceitos gerais' and modulo_id = (select id from public.modulos where nome = 'Teoria Sociológica' and materia_id = (select id from public.materias where nome = 'Sociologia'));
update public.aulas set nivel = 2, resumo = '' where titulo = 'Sociólogos clássicos (Weber, Durkheim, Marx)' and modulo_id = (select id from public.modulos where nome = 'Teoria Sociológica' and materia_id = (select id from public.materias where nome = 'Sociologia'));
update public.modulos set nivel = 2, descricao = '' where nome = 'Trabalho e Produção' and materia_id = (select id from public.materias where nome = 'Sociologia');
update public.aulas set nivel = 5, resumo = '' where titulo = 'Capitalismo e globalização' and modulo_id = (select id from public.modulos where nome = 'Trabalho e Produção' and materia_id = (select id from public.materias where nome = 'Sociologia'));
update public.aulas set nivel = 3, resumo = '' where titulo = 'Modelos de produção (Taylorismo, Fordismo, Toyotismo)' and modulo_id = (select id from public.modulos where nome = 'Trabalho e Produção' and materia_id = (select id from public.materias where nome = 'Sociologia'));
update public.aulas set nivel = 3, resumo = '' where titulo = 'Emprego, desemprego e uberização' and modulo_id = (select id from public.modulos where nome = 'Trabalho e Produção' and materia_id = (select id from public.materias where nome = 'Sociologia'));
update public.modulos set nivel = 2, descricao = '' where nome = 'Movimentos Sociais' and materia_id = (select id from public.materias where nome = 'Sociologia');
update public.aulas set nivel = 4, resumo = '' where titulo = 'Movimentos agrários, urbanos, LGBTQIAPN+ e feminista' and modulo_id = (select id from public.modulos where nome = 'Movimentos Sociais' and materia_id = (select id from public.materias where nome = 'Sociologia'));
update public.aulas set nivel = 3, resumo = '' where titulo = 'Movimento negro' and modulo_id = (select id from public.modulos where nome = 'Movimentos Sociais' and materia_id = (select id from public.materias where nome = 'Sociologia'));
update public.aulas set nivel = 3, resumo = '' where titulo = 'Movimento ambientalista' and modulo_id = (select id from public.modulos where nome = 'Movimentos Sociais' and materia_id = (select id from public.materias where nome = 'Sociologia'));
update public.modulos set nivel = 1, descricao = '' where nome = 'Socialização e Instituições Sociais' and materia_id = (select id from public.materias where nome = 'Sociologia');
update public.aulas set nivel = 5, resumo = '' where titulo = 'Instituição familiar' and modulo_id = (select id from public.modulos where nome = 'Socialização e Instituições Sociais' and materia_id = (select id from public.materias where nome = 'Sociologia'));
update public.aulas set nivel = 4, resumo = '' where titulo = 'Instituição escolar e instituições totais' and modulo_id = (select id from public.modulos where nome = 'Socialização e Instituições Sociais' and materia_id = (select id from public.materias where nome = 'Sociologia'));

-- Filosofia
update public.modulos set nivel = 5, descricao = '' where nome = 'Filosofia Contemporânea' and materia_id = (select id from public.materias where nome = 'Filosofia');
update public.aulas set nivel = 3, resumo = '' where titulo = 'Ética temática (cruzando com Literatura e Sociologia)' and modulo_id = (select id from public.modulos where nome = 'Filosofia Contemporânea' and materia_id = (select id from public.materias where nome = 'Filosofia'));
update public.aulas set nivel = 3, resumo = '' where titulo = 'Escola de Frankfurt e Indústria Cultural (Adorno, Habermas)' and modulo_id = (select id from public.modulos where nome = 'Filosofia Contemporânea' and materia_id = (select id from public.materias where nome = 'Filosofia'));
update public.aulas set nivel = 2, resumo = '' where titulo = 'Rawls e a justiça como equidade' and modulo_id = (select id from public.modulos where nome = 'Filosofia Contemporânea' and materia_id = (select id from public.materias where nome = 'Filosofia'));
update public.aulas set nivel = 2, resumo = '' where titulo = 'Finitude humana' and modulo_id = (select id from public.modulos where nome = 'Filosofia Contemporânea' and materia_id = (select id from public.materias where nome = 'Filosofia'));
update public.aulas set nivel = 2, resumo = '' where titulo = 'Michel Foucault (disciplina, vigilância, micropoder)' and modulo_id = (select id from public.modulos where nome = 'Filosofia Contemporânea' and materia_id = (select id from public.materias where nome = 'Filosofia'));
update public.aulas set nivel = 2, resumo = '' where titulo = 'Nietzsche' and modulo_id = (select id from public.modulos where nome = 'Filosofia Contemporânea' and materia_id = (select id from public.materias where nome = 'Filosofia'));
update public.aulas set nivel = 1, resumo = '' where titulo = 'Hans Jonas e o princípio da responsabilidade' and modulo_id = (select id from public.modulos where nome = 'Filosofia Contemporânea' and materia_id = (select id from public.materias where nome = 'Filosofia'));
update public.aulas set nivel = 1, resumo = '' where titulo = 'Epistemologia da linguagem' and modulo_id = (select id from public.modulos where nome = 'Filosofia Contemporânea' and materia_id = (select id from public.materias where nome = 'Filosofia'));
update public.modulos set nivel = 4, descricao = '' where nome = 'Filosofia Moderna' and materia_id = (select id from public.materias where nome = 'Filosofia');
update public.aulas set nivel = 3, resumo = '' where titulo = 'Maquiavel (o pai da política moderna)' and modulo_id = (select id from public.modulos where nome = 'Filosofia Moderna' and materia_id = (select id from public.materias where nome = 'Filosofia'));
update public.aulas set nivel = 2, resumo = '' where titulo = 'Contratualismo (Hobbes, Locke e Rousseau)' and modulo_id = (select id from public.modulos where nome = 'Filosofia Moderna' and materia_id = (select id from public.materias where nome = 'Filosofia'));
update public.aulas set nivel = 2, resumo = '' where titulo = 'Empirismo (Locke) x racionalismo (Descartes)' and modulo_id = (select id from public.modulos where nome = 'Filosofia Moderna' and materia_id = (select id from public.materias where nome = 'Filosofia'));
update public.aulas set nivel = 2, resumo = '' where titulo = 'Método científico (Bacon, Galileu, Newton)' and modulo_id = (select id from public.modulos where nome = 'Filosofia Moderna' and materia_id = (select id from public.materias where nome = 'Filosofia'));
update public.aulas set nivel = 1, resumo = '' where titulo = 'Iluminismo' and modulo_id = (select id from public.modulos where nome = 'Filosofia Moderna' and materia_id = (select id from public.materias where nome = 'Filosofia'));
update public.aulas set nivel = 1, resumo = '' where titulo = 'Ética em Kant, Hume e Utilitarismo' and modulo_id = (select id from public.modulos where nome = 'Filosofia Moderna' and materia_id = (select id from public.materias where nome = 'Filosofia'));
update public.modulos set nivel = 4, descricao = '' where nome = 'Filosofia Antiga' and materia_id = (select id from public.materias where nome = 'Filosofia');
update public.aulas set nivel = 3, resumo = '' where titulo = 'Sócrates x Sofistas' and modulo_id = (select id from public.modulos where nome = 'Filosofia Antiga' and materia_id = (select id from public.materias where nome = 'Filosofia'));
update public.aulas set nivel = 3, resumo = '' where titulo = 'Aristóteles (Política e Ética)' and modulo_id = (select id from public.modulos where nome = 'Filosofia Antiga' and materia_id = (select id from public.materias where nome = 'Filosofia'));
update public.aulas set nivel = 3, resumo = '' where titulo = 'Pré-socráticos (Tales, Demócrito, Heráclito, Parmênides)' and modulo_id = (select id from public.modulos where nome = 'Filosofia Antiga' and materia_id = (select id from public.materias where nome = 'Filosofia'));
update public.aulas set nivel = 3, resumo = '' where titulo = 'Platão' and modulo_id = (select id from public.modulos where nome = 'Filosofia Antiga' and materia_id = (select id from public.materias where nome = 'Filosofia'));
update public.aulas set nivel = 3, resumo = '' where titulo = 'Helenismo (Epicurismo, Estoicismo, Ceticismo, Cinismo)' and modulo_id = (select id from public.modulos where nome = 'Filosofia Antiga' and materia_id = (select id from public.materias where nome = 'Filosofia'));
update public.aulas set nivel = 1, resumo = '' where titulo = 'Surgimento da Filosofia e a pólis grega' and modulo_id = (select id from public.modulos where nome = 'Filosofia Antiga' and materia_id = (select id from public.materias where nome = 'Filosofia'));
update public.modulos set nivel = 1, descricao = '' where nome = 'Filosofia Medieval' and materia_id = (select id from public.materias where nome = 'Filosofia');
update public.aulas set nivel = 5, resumo = '' where titulo = 'Agostinho (platonismo cristão)' and modulo_id = (select id from public.modulos where nome = 'Filosofia Medieval' and materia_id = (select id from public.materias where nome = 'Filosofia'));
update public.aulas set nivel = 4, resumo = '' where titulo = 'Tomás de Aquino (aristotelismo cristão)' and modulo_id = (select id from public.modulos where nome = 'Filosofia Medieval' and materia_id = (select id from public.materias where nome = 'Filosofia'));

-- Português e Linguagens
update public.modulos set nivel = 5, descricao = '' where nome = 'Interpretação de texto e gêneros textuais' and materia_id = (select id from public.materias where nome = 'Português e Linguagens');
update public.aulas set nivel = 3, resumo = '' where titulo = 'Interpretação de texto' and modulo_id = (select id from public.modulos where nome = 'Interpretação de texto e gêneros textuais' and materia_id = (select id from public.materias where nome = 'Português e Linguagens'));
update public.aulas set nivel = 4, resumo = '' where titulo = 'Fontes jornalísticas (Folha, Estadão, Veja, Época)' and modulo_id = (select id from public.modulos where nome = 'Interpretação de texto e gêneros textuais' and materia_id = (select id from public.materias where nome = 'Português e Linguagens'));
update public.aulas set nivel = 2, resumo = '' where titulo = 'Campanhas de interesse coletivo' and modulo_id = (select id from public.modulos where nome = 'Interpretação de texto e gêneros textuais' and materia_id = (select id from public.materias where nome = 'Português e Linguagens'));
update public.aulas set nivel = 1, resumo = '' where titulo = 'Charges, cartuns e tirinhas' and modulo_id = (select id from public.modulos where nome = 'Interpretação de texto e gêneros textuais' and materia_id = (select id from public.materias where nome = 'Português e Linguagens'));
update public.aulas set nivel = 1, resumo = '' where titulo = 'Texto científico x divulgação científica' and modulo_id = (select id from public.modulos where nome = 'Interpretação de texto e gêneros textuais' and materia_id = (select id from public.materias where nome = 'Português e Linguagens'));
update public.modulos set nivel = 2, descricao = '' where nome = 'Elementos da comunicação e funções da linguagem' and materia_id = (select id from public.materias where nome = 'Português e Linguagens');
update public.aulas set nivel = 3, resumo = 'média de 2 questões por prova' where titulo = 'Funções da linguagem' and modulo_id = (select id from public.modulos where nome = 'Elementos da comunicação e funções da linguagem' and materia_id = (select id from public.materias where nome = 'Português e Linguagens'));
update public.aulas set nivel = 3, resumo = '' where titulo = 'Elementos da comunicação' and modulo_id = (select id from public.modulos where nome = 'Elementos da comunicação e funções da linguagem' and materia_id = (select id from public.materias where nome = 'Português e Linguagens'));
update public.modulos set nivel = 2, descricao = '' where nome = 'Coesão textual' and materia_id = (select id from public.materias where nome = 'Português e Linguagens');
update public.aulas set nivel = 4, resumo = '' where titulo = 'Conjunções e pronomes relativos' and modulo_id = (select id from public.modulos where nome = 'Coesão textual' and materia_id = (select id from public.materias where nome = 'Português e Linguagens'));
update public.aulas set nivel = 4, resumo = '' where titulo = 'Efeitos temporais dos usos verbais' and modulo_id = (select id from public.modulos where nome = 'Coesão textual' and materia_id = (select id from public.materias where nome = 'Português e Linguagens'));
update public.aulas set nivel = 3, resumo = '' where titulo = 'Neologismos e formação de palavras' and modulo_id = (select id from public.modulos where nome = 'Coesão textual' and materia_id = (select id from public.materias where nome = 'Português e Linguagens'));
update public.aulas set nivel = 2, resumo = '' where titulo = 'Ambiguidade e polissemia' and modulo_id = (select id from public.modulos where nome = 'Coesão textual' and materia_id = (select id from public.materias where nome = 'Português e Linguagens'));
update public.modulos set nivel = 1, descricao = '' where nome = 'Figuras de linguagem e texto poético' and materia_id = (select id from public.materias where nome = 'Português e Linguagens');
update public.aulas set nivel = 5, resumo = '' where titulo = 'Figuras de linguagem' and modulo_id = (select id from public.modulos where nome = 'Figuras de linguagem e texto poético' and materia_id = (select id from public.materias where nome = 'Português e Linguagens'));
update public.aulas set nivel = 5, resumo = '' where titulo = 'Métrica (sonetos decassilábicos, versilibrismo)' and modulo_id = (select id from public.modulos where nome = 'Figuras de linguagem e texto poético' and materia_id = (select id from public.materias where nome = 'Português e Linguagens'));
update public.modulos set nivel = 1, descricao = '' where nome = 'Variação linguística' and materia_id = (select id from public.materias where nome = 'Português e Linguagens');
update public.aulas set nivel = 5, resumo = '' where titulo = 'Variação diafásica (linguagem e contexto)' and modulo_id = (select id from public.modulos where nome = 'Variação linguística' and materia_id = (select id from public.materias where nome = 'Português e Linguagens'));
update public.aulas set nivel = 5, resumo = '' where titulo = 'Coloquialidade x norma culta' and modulo_id = (select id from public.modulos where nome = 'Variação linguística' and materia_id = (select id from public.materias where nome = 'Português e Linguagens'));

-- Literatura
update public.modulos set nivel = 3, descricao = 'o tema dominante da Literatura no ENEM' where nome = 'Modernismo' and materia_id = (select id from public.materias where nome = 'Literatura');
update public.aulas set nivel = 3, resumo = 'a maior fatia isolada da matéria' where titulo = 'Modernismo e a relação do leitor com o texto artístico' and modulo_id = (select id from public.modulos where nome = 'Modernismo' and materia_id = (select id from public.materias where nome = 'Literatura'));
update public.aulas set nivel = 3, resumo = '' where titulo = 'Tropicália e Poesia Marginal (Caetano, Gil, Cacaso, Leminski)' and modulo_id = (select id from public.modulos where nome = 'Modernismo' and materia_id = (select id from public.materias where nome = 'Literatura'));
update public.aulas set nivel = 3, resumo = '' where titulo = 'Pré-Modernismo (Policarpo Quaresma, Os Sertões)' and modulo_id = (select id from public.modulos where nome = 'Modernismo' and materia_id = (select id from public.materias where nome = 'Literatura'));
update public.aulas set nivel = 3, resumo = 'autor mais cobrado nos últimos anos' where titulo = 'Prosa contista (Guimarães Rosa)' and modulo_id = (select id from public.modulos where nome = 'Modernismo' and materia_id = (select id from public.materias where nome = 'Literatura'));
update public.modulos set nivel = 2, descricao = '' where nome = 'Realismo' and materia_id = (select id from public.materias where nome = 'Literatura');
update public.aulas set nivel = 5, resumo = '' where titulo = 'Machado de Assis (Memórias Póstumas, Quincas Borba)' and modulo_id = (select id from public.modulos where nome = 'Realismo' and materia_id = (select id from public.materias where nome = 'Literatura'));
update public.aulas set nivel = 3, resumo = '' where titulo = 'Cientificismo do Realismo' and modulo_id = (select id from public.modulos where nome = 'Realismo' and materia_id = (select id from public.materias where nome = 'Literatura'));
update public.modulos set nivel = 3, descricao = '' where nome = 'Romantismo' and materia_id = (select id from public.materias where nome = 'Literatura');
update public.aulas set nivel = 3, resumo = '' where titulo = 'Poesia romântica (Castro Alves, Gonçalves Dias)' and modulo_id = (select id from public.modulos where nome = 'Romantismo' and materia_id = (select id from public.materias where nome = 'Literatura'));
update public.aulas set nivel = 3, resumo = '' where titulo = 'Romance romântico (José de Alencar)' and modulo_id = (select id from public.modulos where nome = 'Romantismo' and materia_id = (select id from public.materias where nome = 'Literatura'));
update public.modulos set nivel = 3, descricao = '' where nome = 'Barroco' and materia_id = (select id from public.materias where nome = 'Literatura');
update public.aulas set nivel = 3, resumo = 'nome predominante do período' where titulo = 'Gregório de Matos' and modulo_id = (select id from public.modulos where nome = 'Barroco' and materia_id = (select id from public.materias where nome = 'Literatura'));
update public.modulos set nivel = 3, descricao = '' where nome = 'Literatura Contemporânea' and materia_id = (select id from public.materias where nome = 'Literatura');
update public.aulas set nivel = 3, resumo = '' where titulo = 'Conceição Evaristo e autores recentes' and modulo_id = (select id from public.modulos where nome = 'Literatura Contemporânea' and materia_id = (select id from public.materias where nome = 'Literatura'));
update public.aulas set nivel = 3, resumo = '' where titulo = 'Clarice Lispector cronista' and modulo_id = (select id from public.modulos where nome = 'Literatura Contemporânea' and materia_id = (select id from public.materias where nome = 'Literatura'));
update public.modulos set nivel = 3, descricao = '' where nome = 'Literatura Portuguesa' and materia_id = (select id from public.materias where nome = 'Literatura');
update public.aulas set nivel = 3, resumo = 'presença pontual (ex.: 2025)' where titulo = 'Camões' and modulo_id = (select id from public.modulos where nome = 'Literatura Portuguesa' and materia_id = (select id from public.materias where nome = 'Literatura'));
update public.modulos set nivel = 3, descricao = '' where nome = 'Interpretação literária' and materia_id = (select id from public.materias where nome = 'Literatura');
update public.aulas set nivel = 3, resumo = '' where titulo = 'Postura dos narradores (1ª x 3ª pessoa)' and modulo_id = (select id from public.modulos where nome = 'Interpretação literária' and materia_id = (select id from public.materias where nome = 'Literatura'));

-- Redação
update public.modulos set nivel = 3, descricao = 'eixos temáticos que mais aparecem na prova' where nome = 'Temas recorrentes' and materia_id = (select id from public.materias where nome = 'Redação');
update public.aulas set nivel = 3, resumo = '' where titulo = 'Questões sociais' and modulo_id = (select id from public.modulos where nome = 'Temas recorrentes' and materia_id = (select id from public.materias where nome = 'Redação'));
update public.aulas set nivel = 3, resumo = '' where titulo = 'Meio ambiente' and modulo_id = (select id from public.modulos where nome = 'Temas recorrentes' and materia_id = (select id from public.materias where nome = 'Redação'));
update public.aulas set nivel = 3, resumo = '' where titulo = 'Tecnologia e sociedade' and modulo_id = (select id from public.modulos where nome = 'Temas recorrentes' and materia_id = (select id from public.materias where nome = 'Redação'));
update public.aulas set nivel = 3, resumo = '' where titulo = 'Cidadania e direitos humanos' and modulo_id = (select id from public.modulos where nome = 'Temas recorrentes' and materia_id = (select id from public.materias where nome = 'Redação'));
